[package]
name = "pocc"
version = "0.1.0"
edition = "2021"
authors = [ "Ritick Madaan <ritickmadaan57@gmail.com>" ]
description = "A CLI to play with postman collections(v2.1.0) inspired by [password-store](https://www.passwordstore.org/)"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
reqwest = { version = "0.11.18", features = ["json"]}
serde = "1.0.163"
serde_json = "1.0.96"
tokio = { version = "1.28.2", features = ["rt-multi-thread", "macros"]}
url = { version = "2.3.1", features = ["serde"] }
